import React, { useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { FileText, Brain, Landmark, MapPin, Send, Download, AtSign, ArrowLeft, Printer, Share2, CheckCircle2, Clock, HardHat, Loader2, X, AlertCircle } from 'lucide-react';
import { cn } from '@/src/lib/utils';
import { db, handleFirestoreError, OperationType } from '@/src/lib/firebase';
import { doc, onSnapshot } from 'firebase/firestore';

export const ReportDetail = () => {
  const [searchParams] = useSearchParams();
  const reportId = searchParams.get('id');
  const navigate = useNavigate();
  const [reportData, setReportData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [showSuccess, setShowSuccess] = useState(false);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  useEffect(() => {
    if (!reportId) {
      navigate('/');
      return;
    }

    const reportRef = doc(db, 'reports', reportId);
    const unsubscribe = onSnapshot(reportRef, (docSnap) => {
      if (docSnap.exists()) {
        setReportData(docSnap.data());
        setLoading(false);
      } else {
        console.warn("Report not found in this snapshot");
        // Don't navigate home immediately, give it a few seconds to propagate
        // or show a not found message instead of a blank screen
        const timer = setTimeout(() => {
          if (!reportData) {
            setLoading(false);
          }
        }, 3000);
        return () => clearTimeout(timer);
      }
    }, (error) => {
      handleFirestoreError(error, OperationType.GET, `reports/${reportId}`);
      setLoading(false);
    });

    return () => unsubscribe();
  }, [reportId, navigate, reportData]);

  if (loading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-surface gap-4">
        <Loader2 className="text-primary animate-spin" size={48} />
        <p className="font-bold text-on-surface-variant animate-pulse uppercase tracking-widest text-xs">Retrieving Civic Intelligence...</p>
      </div>
    );
  }

  if (!reportData) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-surface p-8 text-center">
        <div className="w-20 h-20 rounded-full bg-error/10 text-error flex items-center justify-center mb-6">
          <AlertCircle size={40} />
        </div>
        <h2 className="text-2xl font-bold text-on-surface mb-2">Report Not Found</h2>
        <p className="text-on-surface-variant mb-8 max-w-md">
          We couldn't find the report you're looking for. It might still be processing or the link might be incorrect.
        </p>
        <button 
          onClick={() => navigate('/')}
          className="bg-primary text-white px-8 py-3 rounded-full font-bold shadow-lg"
        >
          Back to Home
        </button>
      </div>
    );
  }

  const downloadReport = () => {
    const content = `
LUMINOUS CIVIC - OFFICIAL REPORT
-------------------------------
Report ID: ${reportData.id}
Date: ${new Date(reportData.createdAt).toLocaleDateString()}

CITIZEN DETAILS:
Name: ${reportData.name}
Address: ${reportData.address}
Email: ${reportData.email || 'N/A'}

ISSUE ANALYSIS:
Type: ${reportData.issueType}
Location: ${reportData.location}
Authority: ${reportData.authority}

LEGAL COMPLAINT:
${reportData.legalComplaint}

-------------------------------
Generated by Luminous Civic AI
    `;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Civic_Report_${reportData.id}.txt`;
    a.click();
  };

  const handlePrint = () => {
    window.print();
  };

  const handleEmail = () => {
    const recipient = "jaysaner14@gmail.com";
    const subject = encodeURIComponent(`Civic Report: ${reportData.issueType} - ${reportData.id}`);
    const body = encodeURIComponent(`Dear ${reportData.authority},\n\nI am reporting a ${reportData.issueType} at ${reportData.address}.\n\nComplaint Details:\n${reportData.legalComplaint}\n\nReport ID: ${reportData.id}\nFiled by: ${reportData.name}\n\nRegards,\n${reportData.name}`);
    
    window.location.href = `mailto:${recipient}?subject=${subject}&body=${body}`;
    
    // Show success popup after a short delay (simulating the action)
    setTimeout(() => {
      setShowSuccess(true);
      setTimeout(() => setShowSuccess(false), 5000);
    }, 1000);
  };

  const getStatusStep = (status: string) => {
    const steps = ['Processing', 'Authority Notified', 'Unit Assigned', 'Resolved'];
    return steps.indexOf(status);
  };

  const currentStepIndex = getStatusStep(reportData.status);

  return (
    <div className="pt-24 pb-32 bg-surface min-h-screen">
      <AnimatePresence>
        {showSuccess && (
          <motion.div 
            initial={{ opacity: 0, y: -100 }}
            animate={{ opacity: 1, y: 20 }}
            exit={{ opacity: 0, y: -100 }}
            className="fixed top-24 left-1/2 -translate-x-1/2 z-50 w-full max-w-md px-4"
          >
            <div className="bg-green-600 text-white p-4 rounded-2xl shadow-2xl flex items-center justify-between">
              <div className="flex items-center gap-3">
                <CheckCircle2 size={24} />
                <div>
                  <p className="font-bold">Email Sent Successfully!</p>
                  <p className="text-xs opacity-90 text-white/80">The authority has been notified of your report.</p>
                </div>
              </div>
              <button onClick={() => setShowSuccess(false)} className="p-1 hover:bg-white/20 rounded-full transition-colors">
                <X size={20} />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="max-w-6xl mx-auto px-8">
        {/* Header Actions */}
        <div className="flex justify-between items-center mb-12 no-print">
          <button 
            onClick={() => navigate('/')}
            className="flex items-center gap-2 text-on-surface-variant hover:text-primary transition-colors font-bold uppercase tracking-widest text-xs"
          >
            <ArrowLeft size={16} />
            Back to Home
          </button>
          <div className="flex gap-4">
            <button 
              onClick={handlePrint}
              className="flex items-center gap-2 px-6 py-3 bg-white border border-outline-variant rounded-full font-bold hover:bg-surface-container-high transition-all shadow-sm"
            >
              <Printer size={18} />
              Print
            </button>
            <button 
              onClick={downloadReport}
              className="flex items-center gap-2 px-6 py-3 bg-primary text-white rounded-full font-bold hover:bg-primary-container transition-all shadow-lg shadow-primary/20"
            >
              <Download size={18} />
              Download
            </button>
          </div>
        </div>

        {/* Main Report Card */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-outline-variant print:shadow-none print:border-none"
        >
          {/* Visual Header */}
          <div className="civic-pulse-gradient p-10 text-white relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-white/10 rounded-full -translate-y-1/2 translate-x-1/2 blur-3xl"></div>
            <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
              <div className="flex items-center gap-6">
                <div className="w-16 h-16 rounded-2xl bg-white/20 backdrop-blur flex items-center justify-center">
                  <FileText size={32} />
                </div>
                <div>
                  <h1 className="font-headline font-extrabold text-3xl md:text-4xl mb-1 tracking-tight">Civic Resolution Report</h1>
                  <div className="flex items-center gap-3 text-white/80 font-bold uppercase tracking-[0.2em] text-xs">
                    <span>ID: {reportData.id}</span>
                    <span className="w-1 h-1 bg-white/40 rounded-full"></span>
                    <span>Filed: {new Date(reportData.createdAt).toLocaleDateString()}</span>
                  </div>
                </div>
              </div>
              <div className="px-6 py-3 bg-white/20 backdrop-blur rounded-full border border-white/30">
                <span className="font-bold uppercase tracking-widest text-xs">Status: {reportData.status}</span>
              </div>
            </div>
          </div>

          <div className="p-8 md:p-16">
            <div className="grid lg:grid-cols-3 gap-16">
              {/* Left Column: Core Data */}
              <div className="lg:col-span-2 space-y-16">
                {/* Citizen Info */}
                <section>
                  <div className="flex items-center gap-3 mb-8">
                    <div className="w-1 h-6 bg-primary rounded-full"></div>
                    <h2 className="font-headline font-bold text-2xl tracking-tight">Citizen Information</h2>
                  </div>
                  <div className="grid md:grid-cols-2 gap-10">
                    <div className="space-y-1">
                      <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest">Reporter Name</p>
                      <p className="text-xl font-bold text-on-surface">{reportData.name}</p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest">Contact Email</p>
                      <p className="text-xl font-bold text-on-surface">{reportData.email || 'Not Provided'}</p>
                    </div>
                    <div className="md:col-span-2 space-y-1">
                      <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest">Reported Address / Landmark</p>
                      <p className="text-xl font-bold text-on-surface">{reportData.address}</p>
                    </div>
                  </div>
                </section>

                {/* Problem Description */}
                {reportData.description && (
                  <section>
                    <div className="flex items-center gap-3 mb-8">
                      <div className="w-1 h-6 bg-amber-500 rounded-full"></div>
                      <h2 className="font-headline font-bold text-2xl tracking-tight">Problem Description</h2>
                    </div>
                    <div className="bg-surface-container-low p-8 rounded-3xl border border-outline-variant">
                      <p className="text-on-surface text-lg leading-relaxed whitespace-pre-wrap">
                        {reportData.description}
                      </p>
                    </div>
                  </section>
                )}

                {/* AI Analysis */}
                <section>
                  <div className="flex items-center gap-3 mb-8">
                    <div className="w-1 h-6 bg-secondary rounded-full"></div>
                    <h2 className="font-headline font-bold text-2xl tracking-tight">AI Analysis & Authority Mapping</h2>
                  </div>
                  <div className="grid md:grid-cols-2 gap-6 mb-10">
                    <div className="bg-surface-container-low p-6 rounded-2xl border border-outline-variant flex items-center gap-5">
                      <div className="w-12 h-12 rounded-xl bg-primary/10 text-primary flex items-center justify-center shrink-0">
                        <Brain size={24} />
                      </div>
                      <div>
                        <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mb-0.5">Detected Issue</p>
                        <p className="font-bold text-lg">{reportData.issueType}</p>
                      </div>
                    </div>
                    <div className="bg-surface-container-low p-6 rounded-2xl border border-outline-variant flex items-center gap-5">
                      <div className="w-12 h-12 rounded-xl bg-secondary/10 text-secondary flex items-center justify-center shrink-0">
                        <Landmark size={24} />
                      </div>
                      <div>
                        <p className="text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mb-0.5">Target Authority</p>
                        <p className="font-bold text-lg">{reportData.authority}</p>
                      </div>
                    </div>
                  </div>
                  <div className="bg-primary/5 p-10 rounded-3xl border-l-8 border-primary relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-4 opacity-10">
                      <FileText size={120} />
                    </div>
                    <p className="text-xs font-bold text-primary uppercase tracking-[0.3em] mb-6">Generated Legal Complaint</p>
                    <p className="text-on-surface text-xl leading-relaxed italic font-medium relative z-10">
                      "{reportData.legalComplaint}"
                    </p>
                  </div>
                </section>

                {/* Resolution Journey */}
                <section className="no-print">
                  <div className="flex items-center gap-3 mb-8">
                    <div className="w-1 h-6 bg-tertiary rounded-full"></div>
                    <h2 className="font-headline font-bold text-2xl tracking-tight">Resolution Journey</h2>
                  </div>
                  <div className="relative space-y-12 pl-10">
                    <div className="absolute left-[19px] top-2 bottom-2 w-0.5 bg-outline-variant"></div>
                    {[
                      { status: "Report Filed", time: "Completed", desc: "Digital report successfully logged in municipal database.", icon: CheckCircle2, active: currentStepIndex >= 0 },
                      { status: "Authority Notified", time: currentStepIndex >= 1 ? "Completed" : "Pending", desc: `Automated dispatch sent to ${reportData.authority} central hub.`, icon: Clock, active: currentStepIndex >= 1 },
                      { status: "Unit Assigned", time: currentStepIndex >= 2 ? "Completed" : "Pending", desc: "Autonomous repair unit allocation and dispatch.", icon: HardHat, active: currentStepIndex >= 2 },
                      { status: "Resolved", time: currentStepIndex >= 3 ? "Completed" : "Pending", desc: "Issue successfully resolved and verified by AI.", icon: CheckCircle2, active: currentStepIndex >= 3 }
                    ].map((step, i) => (
                      <div key={i} className="relative">
                        <div className={cn(
                          "absolute -left-[31px] top-0 w-10 h-10 rounded-full border-4 border-white flex items-center justify-center z-10 transition-all",
                          step.active ? "bg-primary text-white shadow-lg shadow-primary/30 scale-110" : "bg-surface-container-high text-on-surface-variant"
                        )}>
                          <step.icon size={18} />
                        </div>
                        <div>
                          <div className="flex items-center gap-4 mb-2">
                            <h4 className={cn("font-bold text-lg", step.active ? "text-on-surface" : "text-on-surface-variant")}>{step.status}</h4>
                            <span className="px-3 py-0.5 bg-surface-container-high rounded-full text-[10px] font-bold text-on-surface-variant uppercase tracking-widest">{step.time}</span>
                          </div>
                          <p className="text-on-surface-variant leading-relaxed max-w-md">{step.desc}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </section>
              </div>

              {/* Right Column: Evidence & Actions */}
              <div className="space-y-12">
                {/* Evidence */}
                <section>
                  <h3 className="text-xs font-bold text-on-surface-variant uppercase tracking-[0.2em] mb-6 border-b border-outline-variant pb-2">Evidence Capture</h3>
                  <div className="bg-surface-container-low rounded-3xl p-6 border border-outline-variant shadow-sm">
                    <div className="rounded-2xl overflow-hidden mb-6 aspect-square shadow-inner">
                      <img src={reportData.preview} alt="Evidence" className="w-full h-full object-cover" referrerPolicy="no-referrer" />
                    </div>
                    <div className="flex items-center gap-3 text-on-surface-variant">
                      <div className="w-10 h-10 rounded-full bg-white flex items-center justify-center shadow-sm">
                        <MapPin size={18} className="text-primary" />
                      </div>
                      <div>
                        <p className="text-[10px] font-bold uppercase tracking-widest">Captured Location</p>
                        <p className="font-bold text-on-surface text-sm">{reportData.location}</p>
                      </div>
                    </div>
                  </div>
                </section>

                {/* Quick Actions */}
                <section className="no-print">
                  <h3 className="text-xs font-bold text-on-surface-variant uppercase tracking-[0.2em] mb-6 border-b border-outline-variant pb-2">Citizen Actions</h3>
                  <div className="space-y-4">
                    <button 
                      onClick={handleEmail}
                      className="w-full flex items-center justify-center gap-3 bg-primary text-white py-5 rounded-2xl font-bold hover:bg-primary-container transition-all shadow-xl shadow-primary/20 group"
                    >
                      <Send size={20} className="group-hover:translate-x-1 group-hover:-translate-y-1 transition-transform" />
                      Email Authority
                    </button>
                    <button 
                      onClick={() => {
                        if (navigator.share) {
                          navigator.share({
                            title: 'Luminous Civic Report',
                            text: `I just reported a ${reportData.issueType} using Luminous Civic AI!`,
                            url: window.location.href
                          });
                        }
                      }}
                      className="w-full flex items-center justify-center gap-3 bg-white border-2 border-outline-variant text-on-surface py-5 rounded-2xl font-bold hover:bg-surface-container-high transition-all"
                    >
                      <Share2 size={20} />
                      Share Report
                    </button>
                    <button 
                      onClick={() => {
                        navigator.clipboard.writeText(window.location.href);
                        alert("Link copied to clipboard!");
                      }}
                      className="w-full flex items-center justify-center gap-3 bg-secondary/10 text-secondary py-5 rounded-2xl font-bold hover:bg-secondary/20 transition-all"
                    >
                      <AtSign size={20} />
                      Copy Report Link
                    </button>
                  </div>
                </section>

                {/* AI Recommendation */}
                <section className="no-print">
                  <div className="p-8 bg-amber-50 rounded-3xl border border-amber-200 relative overflow-hidden">
                    <div className="absolute top-0 right-0 p-4 text-amber-200">
                      <Brain size={48} />
                    </div>
                    <div className="flex gap-4 relative z-10">
                      <div className="w-10 h-10 rounded-full bg-amber-100 flex items-center justify-center shrink-0">
                        <Clock className="text-amber-600" size={20} />
                      </div>
                      <div>
                        <p className="text-xs font-bold text-amber-800 uppercase tracking-widest mb-2">AI Priority Insight</p>
                        <p className="text-sm text-amber-700 leading-relaxed font-medium">
                          Based on current municipal workloads and the severity of ${reportData.issueType}, we recommend following up if status remains 'Processing' after 72 hours.
                        </p>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>

        </motion.div>
      </div>
      
      {/* Print Styles */}
      <style dangerouslySetInnerHTML={{ __html: `
        @media print {
          .no-print { display: none !important; }
          body { background: white !important; padding: 0 !important; }
          .pt-24 { padding-top: 0 !important; }
          .pb-32 { padding-bottom: 0 !important; }
          .max-w-6xl { max-width: 100% !important; width: 100% !important; }
          .shadow-2xl { box-shadow: none !important; }
          .rounded-3xl { border-radius: 0 !important; }
          .civic-pulse-gradient { background: #1a1a1a !important; color: white !important; -webkit-print-color-adjust: exact; }
          .bg-primary\\/5 { background: #f0f0f0 !important; -webkit-print-color-adjust: exact; }
        }
      `}} />
    </div>
  );
};
